spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development
  application:
    name: app

  h2:
    console:
      enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  address: 0.0.0.0
  port: 8080

  sentry:
    dsn: https://f67680854840febd32def066b4d7ef09@o4509005236797440.ingest.de.sentry.io/4509005373636688
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
    send-default-pii: true
