spring:
  datasource:
    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
    username: hexlet@example.com
    password: qwerty

    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect